# Generated by Django 4.0.10 on 2024-02-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='beta_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
