name: Django CI

on:
  push:
    branches: [ "factual_app" ]
  pull_request:
    branches: [ "factual_app" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
      # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: 'google-github-actions/auth@v1.0.0'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
        service_account: '${{ secrets.SA_EMAIL }}'
    - name: add models folder
      run: |-
        sudo mkdir -p /models
        gsutil -o Credentials:gs_service_key_file=platform-api-389019-c18492c31c22.json cp -r gs://platform-api-389019-tf2-models/models /models
        working-directory: factual/API
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
      working-directory: factual
