name: Django CI

on:
  push:
    branches: [ "factual_app" ]
  pull_request:
    branches: [ "factual_app" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: gsutil authentication
      run: |
        uses: google-github-actions/setup-gcloud@master
        with:
          keyFilename: 'key.json'
        gsutil cp gs://platform-api-389019-tf2-models/models /API/models
    - name: add models folder from cloud storage
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
