name: Django CI

on:
  push:
    branches: [ "factual_app" ]
  pull_request:
    branches: [ "factual_app" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        apt-get update && apt-get install -y --no-install-recommends \
        gcc libc-dev libpq-dev python-dev curl
    - name: gsutil authentication
      run: |
        curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz
        mkdir -p /usr/local/gcloud \
        && tar -C /usr/local/gcloud -xvf /tmp/google-cloud-sdk.tar.gz \
        && /usr/local/gcloud/google-cloud-sdk/install.sh
      env: |
        PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin
    - name: add models folder from cloud storage
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
