name: Django CI

on:
  push:
    branches: [ "factual_app" ]
  pull_request:
    branches: [ "factual_app" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - uses: 'google-github-actions/setup-gcloud@master'
      with:
        credentials_json: ${{ secrets.platform-api-389019-c18492c31c22.json }}'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: add models folder
      run: |
        gsutil cp gs://platform-api-389019-tf2-models/models /API/models
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
